"use client"
import { useState } from "react"
import { api } from "@/lib/api"
import { ComplianceReport } from "@/lib/types"
import { FileBarChart2, Download, Loader2, CheckCircle2, XCircle } from "lucide-react"

const STANDARDS = ["HIPAA", "SOC2", "PCI-DSS"]

function buildMarkdown(report: ComplianceReport): string {
  const lines: string[] = [
    `# PolicyForge Compliance Report`,
    `**Standard:** ${report.standard}`,
    `**Generated:** ${new Date(report.generated_at).toLocaleString()}`,
    ``,
    `## Executive Summary`,
    `| Metric | Value |`,
    `|---|---|`,
    `| Active Policies | ${report.summary.active_policies} |`,
    `| Total Blocked Events | ${report.summary.total_blocked} |`,
    `| Total Events Audited | ${report.summary.total_events} |`,
    ``,
    `## Active Policies`,
    ...report.policies.map(p => `- **${p.name}** — ${p.compliance_tags || "No tags"} (created ${new Date(p.created_at).toLocaleDateString()})`),
    ``,
    `## ${report.standard} Compliance Checklist`,
    ...report.checklist.map(c => `- [${c.status ? "x" : " "}] ${c.item}`),
    ``,
    `## Audit Trail (Last 20 Events)`,
    `| Time | Action | Intent | Rule | Risk |`,
    `|---|---|---|---|---|`,
    ...report.audit_trail.map(l =>
      `| ${new Date(l.timestamp).toLocaleTimeString()} | **${l.action}** | ${l.intent_category} | ${l.matched_rule} | ${(l.risk_score * 100).toFixed(0)}% |`
    ),
    ``,
    `---`,
    `*Report generated by PolicyForge — AI Agent Security Platform*`,
    `*TechEx Intelligent Enterprise Solutions Hackathon 2026*`,
  ]
  return lines.join("\n")
}

export default function ReportPage() {
  const [standard, setStandard] = useState("HIPAA")
  const [report, setReport] = useState<ComplianceReport | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")

  async function generate() {
    setLoading(true)
    setError("")
    try {
      const r = await api.getReport(standard)
      setReport(r)
    } catch (e: any) {
      setError(e.message || "Failed to generate report")
    } finally {
      setLoading(false)
    }
  }

  function download() {
    if (!report) return
    const md = buildMarkdown(report)
    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `policyforge-${standard.toLowerCase()}-report-${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const passCount = report?.checklist.filter(c => c.status).length ?? 0
  const totalCount = report?.checklist.length ?? 0

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Compliance Report</h1>
        <p className="text-sm text-zinc-500 mt-0.5">Generate audit-ready compliance reports for regulators</p>
      </div>

      {/* Controls */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-wrap items-center gap-4">
        <div className="flex gap-2">
          {STANDARDS.map(s => (
            <button
              key={s}
              onClick={() => { setStandard(s); setReport(null) }}
              className={`px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
                standard === s
                  ? "bg-sky-500/15 text-sky-400 border-sky-500/40"
                  : "text-zinc-400 border-zinc-700 hover:border-zinc-500 hover:text-white"
              }`}
            >
              {s}
            </button>
          ))}
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2 bg-sky-500 hover:bg-sky-400 disabled:bg-zinc-700 text-white font-semibold rounded-lg text-sm transition-colors"
        >
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileBarChart2 className="w-4 h-4" />}
          {loading ? "Generating…" : "Generate Report"}
        </button>
        {report && (
          <button
            onClick={download}
            className="flex items-center gap-2 px-4 py-2 bg-emerald-500/15 hover:bg-emerald-500/25 text-emerald-400 border border-emerald-500/30 font-semibold rounded-lg text-sm transition-colors"
          >
            <Download className="w-4 h-4" />
            Download .md
          </button>
        )}
      </div>

      {error && <p className="text-sm text-red-400">{error}</p>}

      {/* Report Preview */}
      {report && (
        <div className="space-y-4">
          {/* Summary Cards */}
          <div className="grid grid-cols-3 gap-4">
            {[
              { label: "Active Policies", value: report.summary.active_policies, color: "text-sky-400" },
              { label: "Blocked Events", value: report.summary.total_blocked, color: "text-red-400" },
              { label: "Checklist Pass", value: `${passCount}/${totalCount}`, color: passCount === totalCount ? "text-emerald-400" : "text-yellow-400" },
            ].map(({ label, value, color }) => (
              <div key={label} className="bg-zinc-900 border border-zinc-800 rounded-xl p-4 text-center">
                <p className={`text-2xl font-black ${color}`}>{value}</p>
                <p className="text-xs text-zinc-500 mt-1">{label}</p>
              </div>
            ))}
          </div>

          {/* Compliance Checklist */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
            <h2 className="font-semibold text-white mb-4">{report.standard} Compliance Checklist</h2>
            <div className="space-y-2.5">
              {report.checklist.map((c, i) => (
                <div key={i} className="flex items-center gap-3">
                  {c.status
                    ? <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
                    : <XCircle className="w-4 h-4 text-red-400 flex-shrink-0" />
                  }
                  <span className={`text-sm ${c.status ? "text-zinc-300" : "text-zinc-500"}`}>{c.item}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Active Policies */}
          {report.policies.length > 0 && (
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h2 className="font-semibold text-white mb-4">Active Policies ({report.policies.length})</h2>
              <div className="space-y-2">
                {report.policies.map((p, i) => (
                  <div key={i} className="flex items-center justify-between py-2 border-b border-zinc-800/50 last:border-0">
                    <span className="text-sm text-white font-mono">{p.name}</span>
                    <span className="text-xs text-zinc-500">{new Date(p.created_at).toLocaleDateString()}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Audit Trail */}
          {report.audit_trail.length > 0 && (
            <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
              <h2 className="font-semibold text-white mb-4">Audit Trail (Last 20 Events)</h2>
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-zinc-800 text-zinc-500">
                    <th className="text-left py-2 pr-3 font-medium">Time</th>
                    <th className="text-left py-2 pr-3 font-medium">Action</th>
                    <th className="text-left py-2 pr-3 font-medium">Intent</th>
                    <th className="text-left py-2 font-medium">Risk</th>
                  </tr>
                </thead>
                <tbody>
                  {report.audit_trail.map((l) => (
                    <tr key={l.id} className="border-b border-zinc-800/40">
                      <td className="py-2 pr-3 text-zinc-500">{new Date(l.timestamp).toLocaleTimeString()}</td>
                      <td className={`py-2 pr-3 font-bold ${l.action === "BLOCK" ? "text-red-400" : "text-emerald-400"}`}>{l.action}</td>
                      <td className="py-2 pr-3 text-zinc-400 font-mono">{l.intent_category}</td>
                      <td className={`py-2 font-bold ${l.risk_score >= 0.7 ? "text-red-400" : "text-yellow-400"}`}>
                        {(l.risk_score * 100).toFixed(0)}%
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {!report && !loading && (
        <div className="flex flex-col items-center justify-center py-20 text-zinc-600">
          <FileBarChart2 className="w-12 h-12 mb-4 opacity-30" />
          <p className="text-sm">Select a standard and generate your compliance report</p>
        </div>
      )}
    </div>
  )
}
